
-- 1

CREATE TABLE TB_CATEGORY (
        NAME VARCHAR(10)
    ,   USE_YN CHAR(1) DEFAULT 'Y'
) ;

-- 1 TABLE 확인
SELECT      *
FROM        TB_CATEGORY ;

-- 1 TABLE 삭제
DROP TABLE TB_CATEGORY ;


-- 2

CREATE TABLE TB_CLASS_TYPE (
        NO VARCHAR2(5)          PRIMARY KEY
    ,   NAME VARCHAR2(10)
) ;

SELECT *
FROM    TB_CLASS_TYPE ;
DROP TABLE TB_CLASS_TYPE ;


-- 3


ALTER TABLE TB_CATEGORY
ADD CONSTRAINT PK_NAME PRIMARY KEY (NAME) ;

SELECT  *
FROM    TB_CATEGORY ;

-- 4

ALTER TABLE TB_CLASS_TYPE
MODIFY (NAME VARCHAR2(10) NOT NULL) ;


-- 5

ALTER TABLE TB_CLASS_TYPE
MODIFY (NO VARCHAR2(10)) ;

ALTER TABLE TB_CATEGORY
MODIFY (NAME VARCHAR2(20)) ;

ALTER TABLE TB_CLASS_TYPE
MODIFY (NAME VARCHAR2(20)) ;


-- 6

ALTER TABLE TB_CATEGORY RENAME TO CATEGORY_NAME ;
ALTER TABLE CATEGORY_NAME RENAME TO TB_CATEGORY ;

ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME ;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO TB_CLASS_TYPE_NAME ;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO TB_CLASS_TYPE_NO ;


SELECT  *
FROM    TB_CATEGORY ;

SELECT  *
FROM    TB_CLASS_TYPE ;

-- 

-- 7 

ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CONSTRAINT PK_NAME TO PK_TB_CLASS_TYPE ;




